### ISSUE TITLE
TemplateDoesNotExist

### ISSUE THREAD

**Issue by olivierdalang** [ninapavlich/django-batch-uploader#1]
Hi,

With django 1.8.5, python 3.4.3, grappelli 2.7.1, after installing following the instructions and opening the admin batch upload page, I get :

```
TemplateDoesNotExist at /admin/ModuleAppuiReconstruction/chantierphoto/
```

for the template

```
admin/batch_change_list.html
```

I don't know anything about pip packages, but I guess the application isn't installed properly, since I can't find the batch_change_list.html file in my python libraries folder.
I made sure I have added the module in settings.py.
If I copy the templates folder to one of my app, the page loads correctly.

**Comment by ninapavlich** [comment]
Hi @olivierdalang,

Thanks so much for letting me know!

I think the package isn't set up correctly for installing from pip. As a workaround you can install the source using this command:

```
pip install -e git+https://github.com/ninapavlich/django-batch-uploader.git@0.7#egg=django_batch_uploader
```

or place this in your requirements.txt:

```
-e git+https://github.com/ninapavlich/django-batch-uploader.git@0.7#egg=django_batch_uploader
```

**Comment by olivierdalang** [comment]
Ok it works this way ! Thanks a lot for super-reactivity and the awesome module !

(still, I guess the issue is still valid since it would be nice to be able to install normally with pip)

**Comment by ninapavlich** [comment]
For sure, I'll keep this open and fix it!

**Comment by ninapavlich** [comment]
Hi @olivierdalang,

I think I got the manifest file working correctly now. You should be able to install using the normal pip command as of tag 0.9:

```
pip uninstall django-batch-uploader
```

Let me know if this works for you and I'll close this thread!

**Comment by olivierdalang** [comment]
Ok it works installing with pip now ! Thanks !
